import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="bg-black text-white flex gap-4 absolute top-20 left-0 p-4 rounded-r-full">
        <Link href="/"> Home</Link>
        <Link href="/about"> About</Link>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
